### ISSUE TITLE
Links no funcionan 

### ISSUE THREAD

**Issue by MatiBravo47** [belenjn/star-wars-app#1]
Hola Belen, antes que nada muy buena tu pagina. Tu link de github pages de Star Wars funciona pero los que estan en tu repositorio subidos en netlify no.

**Comment by belenjn** [comment]
Hola @MatiBravo47 !
Gracias por mecionarlo, estaban los links de netlify porque en un inicio lo desplegué ahí y después, tras arreglar algunas cosas, lo desplegué con GH Pages, se me olvidó eliminar los links antiguos. Ya está actualizado, gracias!
